"""Local, live experiment report. Reads measured results; never fabricates missing metrics."""
import argparse
import json
import time
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[2]
def read(path,default=None):
    try:return json.loads(path.read_text())
    except (FileNotFoundError,json.JSONDecodeError):return default


def update(out):
    artifacts=ROOT/'artifacts';data=artifacts/'dataset-v2';run=artifacts/'run';emb=artifacts/'embedding';out.mkdir(parents=True,exist_ok=True)
    quality=read(data/'quality.json',{});samples=[]
    for split in ['train','val','test','stress']:
        paths=[p for p in sorted((data/split).glob('[0-9]*.json')) if p.with_suffix('.png').exists()]
        for p in paths[:8]:
            m=read(p,{})
            samples.append({'id':split+'/'+p.stem,'image':f'../dataset-v2/{split}/{p.stem}.png','mask':f'../dataset-v2/{split}/{p.stem}_colors.png','prediction':f'../run/{split}/{p.stem}_prediction.png' if (run/split/(p.stem+'_prediction.png')).exists() else None,'lighting':m.get('lighting'),'surface':m.get('background_material'),'film':m.get('transparent_film'),'objects':len(m.get('objects',[])),'height_mm':round(m.get('camera_height_mm',0),1)})
    payload={'updated':time.strftime('%Y-%m-%d %H:%M:%S'),'quality':quality,'progress':read(data/'progress.json',{}),'catalogue':read(artifacts/'catalogue/coverage.json',{}),'history':read(run/'history.json',[]),'metrics':read(run/'metrics.json'),'instances':read(run/'instance_metrics.json'),'model':read(run/'manifest.json'),'embedding_history':read(emb/'history.json',[]),'embedding_metrics':read(emb/'metrics.json'),'embedding_model':read(emb/'manifest.json'),'samples':samples}
    (out/'data.json').write_text(json.dumps(payload))
    if payload['history']:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        h=payload['history'];fig,ax=plt.subplots(1,2,figsize=(11,3.5));epochs=[r['epoch'] for r in h]
        ax[0].plot(epochs,[r['train_loss'] for r in h],label='Training');ax[0].plot(epochs,[r['val_loss'] for r in h],label='Validation');ax[0].set_title('Measured segmentation loss');ax[0].set_xlabel('Epoch');ax[0].legend()
        ax[1].plot(epochs,[r['pill_binary_iou'] for r in h],label='Pill foreground IoU');ax[1].plot(epochs,[r['pill_class_mean_iou'] for r in h],label='Pill-family mean IoU');ax[1].set_ylim(0,1);ax[1].set_xlabel('Epoch');ax[1].legend()
        for a in ax:a.grid(alpha=.2)
        fig.tight_layout();fig.savefig(out/'training-curves.png',dpi=160);plt.close(fig)
    return payload

HTML=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MedTray · Synthetic vision laboratory</title>
<style>
:root{color-scheme:light;--ink:#172b35;--muted:#536b77;--line:#cbd5d7;--blue:#136d85;--paper:#f4f5f0;--orange:#b4591a}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:36px 32px}header{border-top:5px solid var(--ink);padding:22px 0}small,.eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}h1{font-size:clamp(32px,5vw,58px);line-height:1.05;font-weight:550;letter-spacing:-.04em;margin:12px 0}h2{font-size:26px;font-weight:550;margin:30px 0 8px}p{max-width:80ch}nav{display:flex;gap:24px;border-bottom:1px solid var(--line);margin-top:25px;overflow:auto}button{font:inherit;background:none;border:0;padding:13px 0;cursor:pointer;color:var(--muted);white-space:nowrap}button.active{color:var(--ink);border-bottom:3px solid var(--blue)}section{display:none}section.active{display:block}.note{border-left:3px solid var(--orange);padding:10px 18px;background:#eee8d9}.stats{display:flex;flex-wrap:wrap;gap:44px;border-bottom:1px solid var(--line);padding:23px 0}.stat strong{display:block;font-size:29px;font-weight:550}.stat span{color:var(--muted);font-size:12px}.viewer{position:relative;background:#d6dee0;line-height:0}.viewer img{width:100%;display:block}.viewer #mask{position:absolute;inset:0;opacity:.45}.controls{display:flex;gap:20px;flex-wrap:wrap;align-items:center;padding:16px 0}select{padding:8px;border:1px solid var(--line);background:white;font:inherit}input[type=range]{accent-color:var(--blue)}.two{display:grid;grid-template-columns:1fr 1fr;gap:28px}svg{width:100%;height:auto;background:white;border:1px solid var(--line)}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:10px 8px}th{font-weight:600}a{color:var(--blue)}.muted{color:var(--muted)}pre{white-space:pre-wrap;font-size:12px;background:#e7edec;padding:16px}footer{border-top:1px solid var(--line);margin-top:44px;padding-top:18px;font-size:12px;color:var(--muted)}.hero{width:100%;margin:20px 0}.legend{display:flex;gap:18px;font-size:12px;color:var(--muted)}.blue{color:#136d85}.orange{color:#bf6938}@media(max-width:700px){main{padding:18px}.two{grid-template-columns:1fr}.stats{gap:20px}nav{gap:18px}h1{font-size:38px}}
</style><main><header><div class="eyebrow">Austria / Europe · Research prototype · 100% synthetic training</div><h1>Medication trays,<br>from light to labels.</h1><p>Procedural Cycles rendering, exact instance labels, a compact segmentation network, and a rich pill embedding. Every number below comes from the local experiment.</p><div class="note">Research only. These models recognize appearance and visible objects. They do not verify medicine identity, strength, or whether a patient should receive a dose.</div><nav><button class="active" data-tab="dataset">Dataset & realism</button><button data-tab="training">Training & evaluation</button><button data-tab="embedding">Pill embeddings</button><button data-tab="catalogue">Austrian catalogue</button></nav></header>
<section id="dataset" class="active"><div class="stats" id="dataStats"></div><h2>Inspect the training evidence</h2><p class="muted">RGB and geometric semantic masks. Transparent film is removed in the label pass; glare and refraction can conceal or shift the visible appearance. Masks are not amodal.</p><div class="controls"><select id="scene"></select><label>Mask opacity <input id="opacity" type="range" min="0" max="100" value="0"></label><label><input id="prediction" type="checkbox"> Show prediction when available</label></div><div class="viewer"><img id="rgb"><img id="mask" style="opacity:0"></div><p id="sceneMeta" class="muted"></p><h2>What varies</h2><div class="two"><div><p>12 shape families, matte and porous tablets, film coatings, gelatin capsules, softgels, scores, markings, chipped edges, half tablets, fragments and overlap.</p><p>Blue, gray, white and clear molded trays; 3–4 compartments; wood, plastic, laminate and brushed or smudged steel worktops.</p></div><div><p>Enclosed diffused LED lighting with an insertion slot, window light, direct sun and indoor lighting. Height 100–150 mm, lateral position, tilt, roll, focal length, aperture and exposure vary.</p><p>Training adds blur, white-balance changes, noise and JPEG artifacts. Photorealism and real-world transfer remain to be validated against real captures.</p></div></div><h2>Quality audit</h2><div id="qualityTable"></div></section>
<section id="training"><div class="stats" id="trainStats"></div><h2>Loss and validation overlap</h2><div class="legend"><span class="blue">● Training / foreground</span><span class="orange">● Validation / family classes</span></div><div class="two"><div id="lossChart"></div><div id="iouChart"></div></div><p id="trainingState" class="muted"></p><p><a href="training-curves.png">Download training curves</a></p><h2>Held-out synthetic results</h2><div id="resultTable"></div><p class="muted">Foreground IoU measures pill/background separation; family IoU requires the correct appearance class. Instance F1 uses one-to-one mask matching at IoU ≥ 0.5. Exact counts can match even when object identities are wrong.</p><h2>Conditions that change performance</h2><div id="conditionTable"></div></section>
<section id="embedding"><div class="stats" id="embeddingStats"></div><h2>Attributes before product names</h2><p>A 128-dimensional frozen embedding is trained with shape, reflectance color, finish, score, damage, dose-fraction and marking targets. Dimension supervision uses local camera scale; predicted thickness is a learned prior.</p><div id="embeddingChart"></div><div id="embeddingResults"></div><h2>Calibrate with verified references</h2><p>Register cropped pill images, masks, manufacturer, strength and product registration. The reference bank returns candidates ranked by embedding similarity. It does not invent a milligram value from size or color.</p><div class="note">The marking head recognizes only six synthetic strings. This is a narrow baseline, not general OCR. Unreadable imprints, look-alike products, and unknown pills still require review. Reported embedding results use ground-truth synthetic crops.</div><pre>.venv/bin/python -m medtray.calibrate build reference-manifest.json
.venv/bin/python -m medtray.calibrate query pill.png mask.png --bank artifacts/calibration.json</pre></section>
<section id="catalogue"><div class="stats" id="catalogueStats"></div><h2>Official catalogue, explicit coverage</h2><p>The original BASG export is preserved unchanged. A separate derived index filters candidate human oral solid forms. Authorisation does not establish availability, and a form name does not define a unique visible pill.</p><div id="forms"></div><p>16 representative official product descriptions were downloaded and section 3 extracted. Their shape, dimensions, score and marking hints remain unverified drafts. Shared leaflets can describe multiple strengths; none is silently promoted to a verified product model.</p><p><a href="../catalogue/coverage.json">Coverage manifest</a> · <a href="../catalogue/austria_oral_solids.json">Derived catalogue</a> · <a href="../catalogue/appearance_research.json">Appearance research</a></p></section>
<footer>Sources: <a href="https://medikamente.basg.gv.at/de/medicinal-products">BASG register</a> · <a href="https://www.ema.europa.eu/en/documents/presentation/presentation-section-3-pharmaceutical-form_en.pdf">EMA appearance guidance</a> · <a href="https://arxiv.org/abs/2005.14288">ePillID</a> · <a href="https://arxiv.org/abs/1703.06907">Domain randomization</a><br><span id="updated"></span></footer></main>
<script>
let state={},selection='';const $=s=>document.querySelector(s);const pct=x=>x==null?'—':(x*100).toFixed(1)+'%';const num=x=>x==null?'—':Number(x).toLocaleString();const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,section').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
function stats(id,items){$(id).innerHTML=items.map(([v,l])=>`<div class="stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}
function table(head,rows){return `<table><thead><tr>${head.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function chart(id,series,max=null){let flat=series.flatMap(s=>s.values);if(!flat.length){$(id).innerHTML='<p class="muted">Waiting for measured epochs…</p>';return}let hi=max||Math.max(...flat)*1.08,n=Math.max(...series.map(s=>s.values.length)),w=540,h=270,l=48,t=18,b=35,r=18;let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Training metric chart">`;for(let i=0;i<=4;i++){let y=t+i*(h-t-b)/4;svg+=`<line x1="${l}" x2="${w-r}" y1="${y}" y2="${y}" stroke="#e1e6e5"/><text x="8" y="${y+4}" font-size="11" fill="#536b77">${(hi*(1-i/4)).toFixed(2)}</text>`}series.forEach((s,j)=>{let points=s.values.map((v,i)=>`${l+i*(w-l-r)/Math.max(n-1,1)},${h-b-v/hi*(h-t-b)}`).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="${j?'#bf6938':'#136d85'}" stroke-width="2.5"/>`});svg+=`<text x="${l}" y="${h-10}" font-size="11">Epoch 1</text><text x="${w-80}" y="${h-10}" font-size="11">${n}</text></svg>`;$(id).innerHTML=svg}
function showScene(){let s=state.samples.find(s=>s.id==$('#scene').value);if(!s)return;selection=s.id;$('#rgb').src=$('#prediction').checked&&s.prediction?s.prediction:s.image;$('#mask').src=s.mask;$('#mask').style.opacity=$('#opacity').value/100;$('#sceneMeta').textContent=`${s.id} · ${s.lighting} · ${s.surface} · ${s.height_mm} mm camera height · ${s.objects} rendered objects · clear film: ${s.film?'yes':'no'}`}
$('#scene').onchange=showScene;$('#opacity').oninput=showScene;$('#prediction').onchange=showScene;
async function refresh(){try{state=await(await fetch('data.json?t='+Date.now())).json();let q=state.quality.splits||{},total=Object.values(q).reduce((n,s)=>n+s.images,0),objects=Object.values(q).reduce((n,s)=>n+s.objects,0);stats('#dataStats',[[num(total)+'/800','prepared scenes'],[num(objects),'rendered objects'],['12','pill appearance families'],[state.quality.passed?'PASS':'pending','label / split audit']]);let h=state.history,last=h.at(-1);stats('#trainStats',[[num(state.model?.parameters),'segmentation parameters'],[last?.epoch||'—','completed epochs'],[last?last.val_loss.toFixed(3):'—','latest validation loss'],[state.metrics?pct(state.metrics.test.pill_binary_iou):'—','test foreground IoU']]);chart('#lossChart',[{values:h.map(r=>r.train_loss)},{values:h.map(r=>r.val_loss)}]);chart('#iouChart',[{values:h.map(r=>r.pill_binary_iou)},{values:h.map(r=>r.pill_class_mean_iou)}],1);$('#trainingState').textContent=state.metrics?`Selected checkpoint: epoch ${state.metrics.selected_epoch}. All evaluation images are synthetic.`:h.length?'Training in progress. These curves update as epochs finish.':'Dataset rendering / training setup in progress.';
$('#qualityTable').innerHTML=table(['Split','Images','Objects','Empty','Film','Chipped','Stacked'],Object.entries(q).map(([k,v])=>[k,v.images,v.objects,v.empty_scenes,v.film_scenes,v.chipped_objects,v.stacked_objects]));$('#scene').innerHTML=state.samples.map(s=>`<option ${s.id==selection?'selected':''}>${esc(s.id)}</option>`).join('');showScene();
let met=state.metrics,ins=state.instances;$('#resultTable').innerHTML=met?table(['Split','Foreground IoU','Family mean IoU','Instance F1','Count MAE','Exact count'],['test','stress'].map(s=>[s,pct(met[s].pill_binary_iou),pct(met[s].pill_class_mean_iou),pct(ins?.[s].aggregate.instance_f1_iou50),ins?.[s].aggregate.count_mae?.toFixed(2)||'—',pct(ins?.[s].aggregate.exact_count_rate)])):'<p class="muted">Held-out results appear after checkpoint selection.</p>';
$('#conditionTable').innerHTML=ins?table(['Test condition','Scenes','Instance F1','Count MAE'],Object.entries(ins.test.by_condition).map(([k,v])=>[k,v.images,pct(v.instance_f1_iou50),v.count_mae.toFixed(2)])):'<p class="muted">Pending.</p>';
let eh=state.embedding_history,em=state.embedding_metrics;stats('#embeddingStats',[[num(state.embedding_model?.parameters),'encoder parameters'],['128','embedding dimensions'],[eh.length,'completed epochs'],[em?pct(em.test.family_accuracy):'—','test crop family accuracy']]);chart('#embeddingChart',[{values:eh.map(r=>r.train_loss)},{values:eh.map(r=>r.val.loss)}]);$('#embeddingResults').innerHTML=em?table(['Attribute','Test','Stress'],['family_accuracy','finish_accuracy','score_accuracy','damage_accuracy','fraction_accuracy','marking_accuracy'].map(k=>[k.replaceAll('_',' '),pct(em.test[k]),pct(em.stress[k])])):'<p class="muted">Embedding training pending.</p>';
let c=state.catalogue;stats('#catalogueStats',[[num(c.distinct_registrations),'all Austrian registrations'],[num(c.human_registrations),'human registrations'],[num(c.candidate_oral_solid_registrations),'candidate oral solid products'],[num(c.verified_product_models),'verified product models']]);$('#forms').innerHTML=table(['Pharmaceutical form','Registrations'],Object.entries(c.by_form||{}).slice(0,12));$('#updated').textContent='Local results updated '+state.updated;}catch(e){$('#updated').textContent='Waiting for local experiment data…'}}refresh();setInterval(refresh,15000);
</script></html>'''

def main():
    p=argparse.ArgumentParser();p.add_argument('--out',type=Path,default=ROOT/'artifacts/report');p.add_argument('--watch',action='store_true');a=p.parse_args();a.out.mkdir(parents=True,exist_ok=True);(a.out/'index.html').write_text(HTML)
    while True:
        result=update(a.out)
        if not a.watch or result['embedding_metrics']:break
        time.sleep(15)
if __name__=='__main__':main()
