import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {CLASSES as BLENDER_CLASSES,classFor as blenderClass} from '../src/labels/schema.js';
import {trainingTargets as blenderTargets} from '../src/labels/blender-contract.js';
const actual=JSON.parse(readFileSync(new URL('../../configs/classes.json',import.meta.url)));
assert.deepEqual(BLENDER_CLASSES,actual.map(c=>c.name));
for(const [spec,id] of [[{kind:'capsule'},6],[{kind:'softgel'},7],[{kind:'tablet',outline:'round',crownHeight:.05,thickness:3},2],[{kind:'tablet',outline:'round',crownHeight:.5,thickness:3},3],[{kind:'tablet',outline:'polygon',sides:3},9],[{kind:'tablet',outline:'polygon',sides:6},11],[{kind:'tablet',outline:'ring'},12],[{kind:'tablet',outline:'heart'},13]])assert.equal(blenderClass(spec),id);
const s={kind:'capsule',length:20,width:7,capColor:[1,0,0],bodyColor:[1,1,1]};
const pill=(id,spec)=>({instance_id:id,parameters:spec,pose:{position_mm:[12,4,-8],face:null},product_index:0,well:0});
const labels={width:4,height:2,instance:Uint16Array.from([1,10,10,0,1000,500,10,0]),semantic:Uint8Array.from([1,6,6,0,1,14,6,0])};
const meta={seed:1,container:{width_mm:180,depth_mm:60,material:'blue',wells:[{}]},cover:{kind:'none'},config:{},debris:[]};
const a=blenderTargets(labels,[pill(10,s),pill(11,{...s,kind:'tablet',outline:'oval',damage:{fracture:true}})],meta,{});
assert.deepEqual([...a.instance],[1,10,10,0,1000,500,10,0]);
assert.deepEqual([...a.semantic],[1,6,6,0,1,14,6,0]);
assert.deepEqual(a.meta.objects[0].bbox_xyxy,[1,0,3,2]);assert.equal(a.meta.objects[0].visible_pixels,3);
assert.deepEqual(a.meta.objects[0].position_m,[.012,.008,.004]);
assert.equal(a.meta.objects[1].class_id,4);assert.equal(a.meta.objects[1].bbox_xyxy,null);assert.equal(a.meta.objects[1].visible_pixels,0);
for(let i=0;i<a.instance.length;i++)assert.equal(a.meta.instance_to_class[a.instance[i]],a.semantic[i]);
assert.throws(()=>blenderTargets({...labels,instance:Uint16Array.from([99,10,10,0,1000,500,10,0])},[pill(10,s)],meta,{}),/Unmapped pill/);
console.log('PASS: source class table, capsule identity, hidden objects, fractured shape class, debris exclusion, bbox, coordinate conversion, exact lookup');
